// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/proto/transfer/transfer.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FromDeviceId  string                 `protobuf:"bytes,2,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"`
	ToDeviceId    string                 `protobuf:"bytes,3,opt,name=to_device_id,json=toDeviceId,proto3" json:"to_device_id,omitempty"`
	TransferType  string                 `protobuf:"bytes,4,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CreateTransferRequest) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *CreateTransferRequest) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *CreateTransferRequest) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type GetTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferResponse) Reset() {
	*x = GetTransferResponse{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferResponse) ProtoMessage() {}

func (x *GetTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferResponse.ProtoReflect.Descriptor instead.
func (*GetTransferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type UpdateTransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int64                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransferStatusRequest) Reset() {
	*x = UpdateTransferStatusRequest{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferStatusRequest) ProtoMessage() {}

func (x *UpdateTransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTransferStatusRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *UpdateTransferStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTransferStatusRequest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type UpdateTransferStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransferStatusResponse) Reset() {
	*x = UpdateTransferStatusResponse{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferStatusResponse) ProtoMessage() {}

func (x *UpdateTransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransferStatusResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type ListTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransfersRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ListTransfersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type StreamTransferProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTransferProgressRequest) Reset() {
	*x = StreamTransferProgressRequest{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTransferProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTransferProgressRequest) ProtoMessage() {}

func (x *StreamTransferProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTransferProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamTransferProgressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *StreamTransferProgressRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type TransferProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int64                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferProgressUpdate) Reset() {
	*x = TransferProgressUpdate{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgressUpdate) ProtoMessage() {}

func (x *TransferProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgressUpdate.ProtoReflect.Descriptor instead.
func (*TransferProgressUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *TransferProgressUpdate) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferProgressUpdate) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TransferProgressUpdate) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FromDeviceId  string                 `protobuf:"bytes,3,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"`
	ToDeviceId    string                 `protobuf:"bytes,4,opt,name=to_device_id,json=toDeviceId,proto3" json:"to_device_id,omitempty"`
	TransferType  string                 `protobuf:"bytes,5,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int64                  `protobuf:"varint,7,opt,name=progress,proto3" json:"progress,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transfer_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transfer_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *Transfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transfer) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Transfer) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *Transfer) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *Transfer) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *Transfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transfer) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Transfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transfer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_pkg_proto_transfer_transfer_proto protoreflect.FileDescriptor

const file_pkg_proto_transfer_transfer_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/transfer/transfer.proto\x12\btransfer\"\x9d\x01\n" +
	"\x15CreateTransferRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12$\n" +
	"\x0efrom_device_id\x18\x02 \x01(\tR\ffromDeviceId\x12 \n" +
	"\fto_device_id\x18\x03 \x01(\tR\n" +
	"toDeviceId\x12#\n" +
	"\rtransfer_type\x18\x04 \x01(\tR\ftransferType\"H\n" +
	"\x16CreateTransferResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.transfer.TransferR\btransfer\"5\n" +
	"\x12GetTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"E\n" +
	"\x13GetTransferResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.transfer.TransferR\btransfer\"r\n" +
	"\x1bUpdateTransferStatusRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x03R\bprogress\"N\n" +
	"\x1cUpdateTransferStatusResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.transfer.TransferR\btransfer\"G\n" +
	"\x14ListTransfersRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"I\n" +
	"\x15ListTransfersResponse\x120\n" +
	"\ttransfers\x18\x01 \x03(\v2\x12.transfer.TransferR\ttransfers\"@\n" +
	"\x1dStreamTransferProgressRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x8c\x01\n" +
	"\x16TransferProgressUpdate\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x03R\bprogress\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"\x92\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12$\n" +
	"\x0efrom_device_id\x18\x03 \x01(\tR\ffromDeviceId\x12 \n" +
	"\fto_device_id\x18\x04 \x01(\tR\n" +
	"toDeviceId\x12#\n" +
	"\rtransfer_type\x18\x05 \x01(\tR\ftransferType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x03R\bprogress\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt2\xd2\x03\n" +
	"\x0fTransferService\x12S\n" +
	"\x0eCreateTransfer\x12\x1f.transfer.CreateTransferRequest\x1a .transfer.CreateTransferResponse\x12J\n" +
	"\vGetTransfer\x12\x1c.transfer.GetTransferRequest\x1a\x1d.transfer.GetTransferResponse\x12e\n" +
	"\x14UpdateTransferStatus\x12%.transfer.UpdateTransferStatusRequest\x1a&.transfer.UpdateTransferStatusResponse\x12P\n" +
	"\rListTransfers\x12\x1e.transfer.ListTransfersRequest\x1a\x1f.transfer.ListTransfersResponse\x12e\n" +
	"\x16StreamTransferProgress\x12'.transfer.StreamTransferProgressRequest\x1a .transfer.TransferProgressUpdate0\x01B0Z.github.com/backend-app/backend/pkg/proto/transferb\x06proto3"

var (
	file_pkg_proto_transfer_transfer_proto_rawDescOnce sync.Once
	file_pkg_proto_transfer_transfer_proto_rawDescData []byte
)

func file_pkg_proto_transfer_transfer_proto_rawDescGZIP() []byte {
	file_pkg_proto_transfer_transfer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_transfer_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_transfer_transfer_proto_rawDesc), len(file_pkg_proto_transfer_transfer_proto_rawDesc)))
	})
	return file_pkg_proto_transfer_transfer_proto_rawDescData
}

var file_pkg_proto_transfer_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_transfer_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil),         // 0: transfer.CreateTransferRequest
	(*CreateTransferResponse)(nil),        // 1: transfer.CreateTransferResponse
	(*GetTransferRequest)(nil),            // 2: transfer.GetTransferRequest
	(*GetTransferResponse)(nil),           // 3: transfer.GetTransferResponse
	(*UpdateTransferStatusRequest)(nil),   // 4: transfer.UpdateTransferStatusRequest
	(*UpdateTransferStatusResponse)(nil),  // 5: transfer.UpdateTransferStatusResponse
	(*ListTransfersRequest)(nil),          // 6: transfer.ListTransfersRequest
	(*ListTransfersResponse)(nil),         // 7: transfer.ListTransfersResponse
	(*StreamTransferProgressRequest)(nil), // 8: transfer.StreamTransferProgressRequest
	(*TransferProgressUpdate)(nil),        // 9: transfer.TransferProgressUpdate
	(*Transfer)(nil),                      // 10: transfer.Transfer
}
var file_pkg_proto_transfer_transfer_proto_depIdxs = []int32{
	10, // 0: transfer.CreateTransferResponse.transfer:type_name -> transfer.Transfer
	10, // 1: transfer.GetTransferResponse.transfer:type_name -> transfer.Transfer
	10, // 2: transfer.UpdateTransferStatusResponse.transfer:type_name -> transfer.Transfer
	10, // 3: transfer.ListTransfersResponse.transfers:type_name -> transfer.Transfer
	0,  // 4: transfer.TransferService.CreateTransfer:input_type -> transfer.CreateTransferRequest
	2,  // 5: transfer.TransferService.GetTransfer:input_type -> transfer.GetTransferRequest
	4,  // 6: transfer.TransferService.UpdateTransferStatus:input_type -> transfer.UpdateTransferStatusRequest
	6,  // 7: transfer.TransferService.ListTransfers:input_type -> transfer.ListTransfersRequest
	8,  // 8: transfer.TransferService.StreamTransferProgress:input_type -> transfer.StreamTransferProgressRequest
	1,  // 9: transfer.TransferService.CreateTransfer:output_type -> transfer.CreateTransferResponse
	3,  // 10: transfer.TransferService.GetTransfer:output_type -> transfer.GetTransferResponse
	5,  // 11: transfer.TransferService.UpdateTransferStatus:output_type -> transfer.UpdateTransferStatusResponse
	7,  // 12: transfer.TransferService.ListTransfers:output_type -> transfer.ListTransfersResponse
	9,  // 13: transfer.TransferService.StreamTransferProgress:output_type -> transfer.TransferProgressUpdate
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_transfer_transfer_proto_init() }
func file_pkg_proto_transfer_transfer_proto_init() {
	if File_pkg_proto_transfer_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_transfer_transfer_proto_rawDesc), len(file_pkg_proto_transfer_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_transfer_transfer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_transfer_transfer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_transfer_transfer_proto_msgTypes,
	}.Build()
	File_pkg_proto_transfer_transfer_proto = out.File
	file_pkg_proto_transfer_transfer_proto_goTypes = nil
	file_pkg_proto_transfer_transfer_proto_depIdxs = nil
}
